kind: Service
apiVersion: v1
metadata:
  name: echo-server
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind: Mapping
      name: echo-server-mapping
      service: echo-server:80
      prefix: /echo/
      host: example.com
spec:
  selector:
    app: echo-server
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-server
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
  selector:
    matchLabels:
      app: echo-server
  template:
    metadata:
      labels:
        app: echo-server
    spec:
      containers:
        - name: echo-server
          image: mendhak/http-https-echo
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              path: /
              port: 80
